package com.ecobridge.controller;
import com.ecobridge.entity.*; import com.ecobridge.repository.*;
import jakarta.servlet.http.HttpSession; import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
import java.time.*; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController {
 private final PickupRepository pickups; private final EventRepository events; private final FeedPostRepository posts;
 public ApiController(PickupRepository p,EventRepository e,FeedPostRepository f){pickups=p;events=e;posts=f;seed();}
 private void seed(){if(events.count()==0){events.save(event("Mula River Cleanup","Restore the riverbank with a friendly local team.",LocalDate.now().plusDays(6),"07:30 AM","Mula River Walk, Pune",80,"https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=1200&q=80","Green Pune Collective",47));events.save(event("Urban Tree Plantation","Plant native shade trees and learn long-term care.",LocalDate.now().plusDays(12),"08:00 AM","Aundh Biodiversity Park",120,"https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80","EcoBridge Campus",86));}if(posts.count()==0){posts.save(post(null,"Anaya Mehta","Our street is 14 bags lighter today. Small teams make a huge difference!","Neighbourhood cleanup","https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=1200&q=80",128));posts.save(post(null,"Rohan & the Green Club","Planted 20 native saplings on campus. Now the real work begins.","Tree plantation","https://images.unsplash.com/photo-1599685315640-9ceab2f581ca?auto=format&fit=crop&w=1200&q=80",243));}}
 private EcoEventEntity event(String n,String d,LocalDate date,String time,String loc,int cap,String img,String org,int reg){var e=new EcoEventEntity();e.setName(n);e.setDescription(d);e.setDate(date);e.setTime(time);e.setLocation(loc);e.setCapacity(cap);e.setImageUrl(img);e.setOrganizer(org);e.setRegistered(reg);return e;}
 private FeedPost post(Long uid,String author,String caption,String activity,String image,int likes){var p=new FeedPost();p.setUserId(uid);p.setAuthor(author);p.setCaption(caption);p.setActivity(activity);p.setImageUrl(image);p.setLikes(likes);return p;}
 private Long userId(HttpSession s){return (Long)s.getAttribute("userId");} private Long requireUser(HttpSession s){var id=userId(s);if(id==null)throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED,"Please log in first");return id;} private String userName(HttpSession s){return Optional.ofNullable((String)s.getAttribute("userName")).orElse("EcoBridge Member");}
 @GetMapping("/pickups") public List<PickupRequest> pickupList(){return pickups.findAllByOrderByCreatedAtDesc();}
 @PostMapping("/pickups") @ResponseStatus(HttpStatus.CREATED) public PickupRequest createPickup(@Valid @RequestBody PickupInput in,HttpSession s){var p=new PickupRequest();p.setUserId(requireUser(s));p.setWasteType(in.wasteType());p.setQuantity(in.quantity());p.setImageUrl(in.imageUrl());p.setAddress(in.address());p.setPreferredDate(in.preferredDate());p.setPreferredTime(in.preferredTime());p.setNotes(in.notes());p.setStatus("Requested");return pickups.save(p);}
 @GetMapping("/events") public List<EcoEventEntity> eventList(){return events.findAllByOrderByDateAsc();}
 @PostMapping("/events") @ResponseStatus(HttpStatus.CREATED) public EcoEventEntity createEvent(@Valid @RequestBody EventInput in,HttpSession s){var e=event(in.name(),in.description(),in.date(),in.time(),in.location(),in.capacity(),in.imageUrl(),userName(s),0);e.setOrganizerId(requireUser(s));return events.save(e);}
 @PostMapping("/events/{id}/join") public EcoEventEntity join(@PathVariable Long id){var e=events.findById(id).orElseThrow();if(e.getRegistered()<e.getCapacity())e.setRegistered(e.getRegistered()+1);return events.save(e);}
 @DeleteMapping("/events/{id}/join") public EcoEventEntity leave(@PathVariable Long id){var e=events.findById(id).orElseThrow();e.setRegistered(Math.max(0,e.getRegistered()-1));return events.save(e);}
 @GetMapping("/posts") public List<FeedPost> postList(){return posts.findAllByOrderByCreatedAtDesc();}
 @PostMapping("/posts") @ResponseStatus(HttpStatus.CREATED) public FeedPost createPost(@Valid @RequestBody PostInput in,HttpSession s){return posts.save(post(requireUser(s),userName(s),in.caption(),in.activity(),in.imageUrl(),0));}
 @PostMapping("/posts/{id}/like") public FeedPost like(@PathVariable Long id){var p=posts.findById(id).orElseThrow();p.setLikes(p.getLikes()+1);return posts.save(p);}
 @DeleteMapping("/posts/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deletePost(@PathVariable Long id,HttpSession s){var p=posts.findById(id).orElseThrow();if(!Objects.equals(p.getUserId(),requireUser(s)))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.FORBIDDEN,"You can only delete your own post");posts.delete(p);}
 public record PickupInput(@NotBlank String wasteType,@Positive double quantity,String imageUrl,@NotBlank String address,@NotNull @FutureOrPresent LocalDate preferredDate,@NotBlank String preferredTime,String notes){}
 public record EventInput(@NotBlank String name,@NotBlank String description,@NotNull LocalDate date,@NotBlank String time,@NotBlank String location,@Positive int capacity,String imageUrl){}
 public record PostInput(@NotBlank @Size(max=4000) String caption,String activity,String imageUrl){}
}
