package com.ecobridge.controller;
import com.ecobridge.config.FirebaseService; import com.ecobridge.entity.AppUser; import com.ecobridge.repository.AppUserRepository;
import jakarta.servlet.http.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
import java.util.*;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private final AppUserRepository users; private final PasswordEncoder encoder; private final FirebaseService firebase;
 public AuthController(AppUserRepository u,PasswordEncoder e,FirebaseService f){users=u;encoder=e;firebase=f;}
 @PostMapping("/signup") public ResponseEntity<?> signup(@Valid @RequestBody Signup in,HttpSession s){if(users.findByEmailIgnoreCase(in.email()).isPresent())return ResponseEntity.status(409).body(Map.of("message","An account already exists for this email."));var u=new AppUser();u.setName(in.name().trim());u.setEmail(in.email().trim().toLowerCase());u.setPasswordHash(encoder.encode(in.password()));u=users.save(u);loginSession(s,u);return ResponseEntity.status(201).body(view(u));}
 @PostMapping("/login") public ResponseEntity<?> login(@Valid @RequestBody Login in,HttpSession s){var u=users.findByEmailIgnoreCase(in.email()).orElse(null);if(u==null||u.getPasswordHash()==null||!encoder.matches(in.password(),u.getPasswordHash()))return ResponseEntity.status(401).body(Map.of("message","Invalid email or password."));loginSession(s,u);return ResponseEntity.ok(view(u));}
 @GetMapping("/me") public ResponseEntity<?> me(HttpSession s){var id=(Long)s.getAttribute("userId");return id==null?ResponseEntity.status(401).body(Map.of("message","Not signed in")):users.findById(id).<ResponseEntity<?>>map(u->ResponseEntity.ok(view(u))).orElseGet(()->ResponseEntity.status(401).body(Map.of("message","Not signed in")));}
 @PostMapping("/logout") public Map<String,String> logout(HttpSession s){s.invalidate();return Map.of("message","Signed out");}
 @PostMapping("/firebase-session") public ResponseEntity<?> firebaseSession(@RequestBody Map<String,String> body,HttpSession s){try{var token=firebase.verify(body.getOrDefault("idToken",""));var email=token.getEmail();if(email==null||email.isBlank())return ResponseEntity.badRequest().body(Map.of("message","Firebase account has no email address"));var user=users.findByFirebaseUid(token.getUid()).orElseGet(()->users.findByEmailIgnoreCase(email).orElseGet(AppUser::new));user.setFirebaseUid(token.getUid());user.setEmail(email.toLowerCase());user.setName(Optional.ofNullable(token.getName()).filter(n->!n.isBlank()).orElseGet(()->Optional.ofNullable(body.get("name")).filter(n->!n.isBlank()).orElse("EcoBridge Member")));user.setAvatarUrl(token.getPicture());user.setProvider("FIREBASE");user=users.save(user);loginSession(s,user);return ResponseEntity.ok(view(user));}catch(Exception e){return ResponseEntity.status(401).body(Map.of("message","Firebase authentication failed: "+e.getMessage()));}}
 @GetMapping("/google-status") public Map<String,Object> googleStatus(@Value("${spring.security.oauth2.client.registration.google.client-id:}") String id){return Map.of("configured",!id.isBlank());}
 private void loginSession(HttpSession s,AppUser u){s.setAttribute("userId",u.getId());s.setAttribute("userName",u.getName());s.setAttribute("userEmail",u.getEmail());}
 private Map<String,Object> view(AppUser u){return Map.of("id",u.getId(),"name",u.getName(),"email",u.getEmail(),"provider",u.getProvider());}
 public record Signup(@NotBlank String name,@Email @NotBlank String email,@Size(min=6,max=72) String password){} public record Login(@Email @NotBlank String email,@NotBlank String password){}
}
