spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
server.servlet.session.cookie.secure=true
server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
