package com.ecobridge.entity;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*;
@Entity @Table(name="pickup_requests") public class PickupRequest {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="client_request_id",nullable=false,unique=true,length=64) private String clientRequestId; @Column(name="user_id",nullable=false) private Long userId; @Column(name="collector_id") private Long collectorId;
 @Column(name="waste_type",nullable=false,length=50) private String wasteType; @Column(name="quantity_kg",nullable=false,precision=10,scale=2) private BigDecimal quantity; @Column(name="pickup_address",nullable=false,columnDefinition="TEXT") private String address; @Column(precision=10,scale=7) private BigDecimal latitude; @Column(precision=10,scale=7) private BigDecimal longitude;
 @Column(name="preferred_date",nullable=false) private LocalDate preferredDate; @Column(name="preferred_time") private LocalTime preferredTime; @Column(columnDefinition="TEXT") private String notes; @Column(name="image_url",columnDefinition="TEXT") private String imageUrl; @Column(nullable=false,length=40) private String status="REQUESTED";
 @Column(name="created_at",nullable=false,updatable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="accepted_at") private Instant acceptedAt; @Column(name="collected_at") private Instant collectedAt; @Column(name="completed_at") private Instant completedAt; @Column(name="cancelled_at") private Instant cancelledAt;
 @PrePersist void create(){var n=Instant.now();if(createdAt==null)createdAt=n;updatedAt=n;} @PreUpdate void update(){updatedAt=Instant.now();}
 public Long getId(){return id;} public Long getUserId(){return userId;} public void setUserId(Long v){userId=v;} public Long getCollectorId(){return collectorId;} public void setCollectorId(Long v){collectorId=v;} public String getWasteType(){return wasteType;} public void setWasteType(String v){wasteType=v;} public double getQuantity(){return quantity==null?0:quantity.doubleValue();} public void setQuantity(double v){quantity=BigDecimal.valueOf(v);} public String getImageUrl(){return imageUrl;} public void setImageUrl(String v){imageUrl=v;} public String getAddress(){return address;} public void setAddress(String v){address=v;} public LocalDate getPreferredDate(){return preferredDate;} public void setPreferredDate(LocalDate v){preferredDate=v;} public String getPreferredTime(){return preferredTime==null?null:preferredTime.toString();} public void setPreferredTime(String v){preferredTime=v==null||v.isBlank()?null:LocalTime.parse(v.split("\\s")[0]);} public String getNotes(){return notes;} public void setNotes(String v){notes=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public Instant getAcceptedAt(){return acceptedAt;} public void setAcceptedAt(Instant v){acceptedAt=v;} public Instant getCollectedAt(){return collectedAt;} public void setCollectedAt(Instant v){collectedAt=v;} public Instant getCompletedAt(){return completedAt;} public void setCompletedAt(Instant v){completedAt=v;} public Instant getCancelledAt(){return cancelledAt;} public void setCancelledAt(Instant v){cancelledAt=v;} public Instant getUpdatedAt(){return updatedAt;} public Instant getCreatedAt(){return createdAt;}
 public String getClientRequestId(){return clientRequestId;} public void setClientRequestId(String v){clientRequestId=v;}
}
