package com.ecobridge.entity;
import jakarta.persistence.*; import java.time.Instant;
@Entity @Table(name="users") public class User {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="google_id",unique=true,length=255) private String googleId;
 @Column(nullable=false,length=150) private String name; @Column(nullable=false,unique=true,length=255) private String email; @Column(length=20) private String phone; @Column(columnDefinition="TEXT") private String address; @Column(length=255) private String location;
 @Column(name="profile_image_url",columnDefinition="TEXT") private String profileImageUrl; @Column(name="password_hash",length=100) private String passwordHash; @Column(nullable=false,length=30) private String role="ROLE_USER"; @Column(name="account_status",nullable=false,length=30) private String accountStatus="ACTIVE";
 @Column(name="created_at",nullable=false,updatable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
 @PrePersist void create(){var n=Instant.now();if(createdAt==null)createdAt=n;updatedAt=n;email=email.trim().toLowerCase();} @PreUpdate void update(){updatedAt=Instant.now();email=email.trim().toLowerCase();}
 public Long getId(){return id;} public String getGoogleId(){return googleId;} public void setGoogleId(String v){googleId=v;} public String getName(){return name;} public void setName(String v){name=v;} public String getEmail(){return email;} public void setEmail(String v){email=v;} public String getPhone(){return phone;} public void setPhone(String v){phone=v;} public String getAddress(){return address;} public void setAddress(String v){address=v;} public String getLocation(){return location;} public void setLocation(String v){location=v;} public String getProfileImageUrl(){return profileImageUrl;} public void setProfileImageUrl(String v){profileImageUrl=v;} public String getPasswordHash(){return passwordHash;} public void setPasswordHash(String v){passwordHash=v;} public String getRole(){return role;} public void setRole(String v){role=v;} public String getAccountStatus(){return accountStatus;} public void setAccountStatus(String v){accountStatus=v;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;}
}
